
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: travelagency
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: donotcrackplease
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api: 
    build: .
    environment:
      POSTGRES_CONN_STR: "postgres://admin:donotcrackplease@database/travelagency?sslmode=disable"
      REDIS_ADDR: "redis:6379"
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
